### ISSUE TITLE
##[error]You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by RobBarat** [XpiritBV/Xpirit-Vsts-Release-Terraform#36]
When running Terraform task, an error is received.

Terraform have changed the response from https://releases.hashicorp.com/terraform/
https://github.com/hashicorp/terraform/issues/31024

![image](https://user-images.githubusercontent.com/25378721/167752954-db62b71f-399d-4fa7-9786-e2dff0ab2676.png)

**Comment by RobBarat** [comment]
Temporary resolution
![image](https://user-images.githubusercontent.com/25378721/167753462-072f319e-75ff-49d8-b7fd-95830d3be4ad.png)

**Comment by RobBarat** [comment]
Unable to push a fix through to raise pull request unfortunately. Hope someone could make the change if it's acceptable.

**Comment by DevKyleS** [comment]
@RobBarat I forked and just commented out the code yesterday to address my urgent needs, if your version fixes this Ill add to my forked version.

**Comment by RobBarat** [comment]
Just checked, what you have is exactly all that is needed to change.
Thank you for raising the pull request.

**Comment by DevKyleS** [comment]
For those that need an urgent fix, I had published my fork which can be found [here](https://marketplace.visualstudio.com/items?itemName=DevKyleS.DevKyleS-Xpirit-Vsts-Release-Terraform)

**Comment by pgroene** [comment]
I published a new version to the marketplace, can anyone verify the extension is working again?

**Comment by exolain** [comment]
Hi @pgroene , I had a deployment waiting for this change... I've re-deployed it and it is working as expected now. Thank you 😄

**Comment by RohanKarshikar** [comment]
This is now working, thank you :)

**Comment by lha-ryq** [comment]
The problem is back. I am not able to run the Terraform task with the latest plugin version.

```
2022-06-20T19:44:32.5378821Z ##[section]Starting: Terraform init backend
2022-06-20T19:44:32.5702571Z ==============================================================================
2022-06-20T19:44:32.5703186Z Task         : Run Terraform
2022-06-20T19:44:32.5704610Z Description  : Run a Terraform on the build agent
2022-06-20T19:44:32.5705039Z Version      : 2.5.0
2022-06-20T19:44:32.5705292Z Author       : Peter Groenewegen - Xpirit
2022-06-20T19:44:32.5706296Z Help         : [More Information](https://pgroene.wordpress.com/2016/06/14/getting-started-with-terraform-on-windows-and-azure/)
2022-06-20T19:44:32.5706832Z ==============================================================================
2022-06-20T19:44:40.5810377Z ##[error]You cannot call a method on a null-valued expression.
2022-06-20T19:44:40.6630150Z ##[section]Finishing: Terraform init backend
```

**Comment by lha-ryq** [comment]
It looks like the response from https://releases.hashicorp.com/terraform/ has again the old format and a new regex does not work.

I think we should use something like this: `"""/terraform/([0-9]+\.[0-9]+\.[0-9]+)/?"""`
I am not able to test it as I don't own any Windows machine.

**Comment by lha-ryq** [comment]
If we would like to get rid of these problems then we should start using https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api

**Comment by pgroene** [comment]
I'll have a look tomorrow, if you have the correct regex I'll bake a new
version of the extension.

**Comment by itchy-squid** [comment]
For what it's worth, my team was able to get around this issue by moving the Terraform installation to its own task. [ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks)

**Comment by aspan1** [comment]
Hi @pgroene - any update on the new extension version?  I have some deployments awaiting.  Many thanks!

**Comment by xbeijeman** [comment]
> For what it's worth, my team was able to get around this issue by moving the Terraform installation to its own task. [ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks)

We have the same problem with the extension, and this workaround is also the solution for us, thanks for that!

**Comment by pgroene** [comment]
Fix the issue in PR #39 ,  please confirm if it is indeed fixed. I would recommend to look into moving to an extension like mentioned above to have more support. I do not have a lot of time to fix issues if there are any, in case I'm on vacation for example I do not have an computer to upload any new versions to the marketplace. For now the extension should be in a working state.

**Comment by aspan1** [comment]
@pgroene Thank you, yes we are testing the extension mentioned and will report back on your revision.

**Comment by lha-ryq** [comment]
@pgroene I have tested the latest version and it works for me. Thanks!
